# Generated by Django 3.2.5 on 2021-08-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavemanagementsys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='Leave_type',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('P', 'Personal'), ('L', 'LOP_Leave'), ('C', 'Covid_Support')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('A', 'Approve'), ('R', 'Reject'), ('P', 'Pending'), ('C', 'Cancel')], default='P', max_length=1),
        ),
    ]
