# Generated by Django 3.2.5 on 2021-08-05 11:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leavemanagementsys', '0002_leaverequest_applied_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='from_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='to_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
